apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "atakama-srv-aggregator.fullname" . }}
  labels:
    {{- include "atakama-srv-aggregator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "atakama-srv-aggregator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "atakama-srv-aggregator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "atakama-srv-aggregator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "ATK_SRV_IMPORT_DIR"
              value: "{{ .Values.config.dashboardImportDir }}"
            - name: "ATK_SRV_ENABLE_LOGGING_TO_FILE"
              value: "{{ .Values.config.dashboardEnableFileLog }}"
            {{- if .Values.config.dashboardInitDb }}
            - name: "ATK_SRV_DASHBOARD__INIT_DB"
              value: "{{ .Values.config.dashboardInitDb }}"
            {{- end }}
            {{- with .Values.environment }}
              {{- toYaml . |  nindent 12 }}
            {{- end}}
          envFrom:
            - secretRef:
                name: {{ .Values.config.dashboardDbSecret }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
